menu:
  Home: /
  Archives: archives
  page:
    About: about
    Archives: archives

excerpt_link: Continue →

social:
  twitter: true
  github: true
  linkedin: true
  rss: true

twitter:
  username: ericabouaf

linkedin:
  username: ericabouaf

github:
  username: ericabouaf

google_analytics: UA-567557-1
