menu:
  Home: /
  Archives: archives
  page:
    About: about
    Archives: archives

excerpt_link: Continue →

mathjax: true
fancybox: true

social:
  twitter: true
  github: true
  linkedin: true
  delicious: false
  facebook: false
  rss: true

twitter:
  username: ericabouaf

linkedin:
  username: ericabouaf

github:
  username: ericabouaf

google_analytics: UA-567557-1

addit:
  facebook: false
  twitter: true
  gplus: true
  pinit: false
  publid:
